trigger:
  branches:
    include:     
      - main

pool:
  name: Default

stages:
- stage: Build
  displayName: 'Deploy from Published Artifact'
  jobs:
  - job: CI
    displayName: 'Continuous Integration'
    steps:
    - task: UseDotNet@2
      displayName: 'Install .NET Core SDK'
      inputs:
        packageType: 'sdk'
        version: '8.x'  

    - task: NuGetCommand@2
      displayName: 'NuGet Restore'
      inputs:
        command: 'restore'
        restoreSolution: '**/*.sln'
        feedsToUse: 'config'
        nugetConfigPath: 'NuGet.config'

    - script: dotnet build --configuration Release
      displayName: 'Build application'

    - script: dotnet publish --configuration Release --output $(Build.ArtifactStagingDirectory)
      displayName: 'Publish Application'
    
    - task: PublishBuildArtifacts@1
      displayName: 'Publish Build Artifacts'
      inputs:
        pathtoPublish: '$(Build.ArtifactStagingDirectory)'
        ArtifactName: 'drop'
        publishLocation: Container

- stage: DeployQA
  displayName: 'Deploy to QA'
  dependsOn: Build
  jobs:
  - job: CDQA
    displayName: 'Continuous Deployment to QA'
    steps:
    - download: current
      artifact: drop
      displayName: 'Download Build Artifacts'

    - task: UseDotNet@2
      displayName: 'Install .NET Core SDK'
      inputs:
        packageType: 'sdk'
        version: '8.x'  

# - stage: DeployUAT
#   displayName: 'Deploy to UAT'
#   dependsOn: DeployQA
#   jobs:  
#   - deployment: 'DeploytoUAT'
#     displayName: 'DeployUAT'
#     environment: 'UAT'
#     strategy:
#       runOnce:
#         deploy:
#           steps:
#             - download: current
#               artifact: drop
#               displayName: 'Download Build Artifacts'           
    
#             - task: UseDotNet@2
#               displayName: 'Install .NET Core SDK'
#               inputs:
#                 packageType: 'sdk'
#                 version: '8.x'  

#             - task: AzureRmWebAppDeployment@4
#               displayName: 'Azure Web App Deploy to UAT'
#               inputs:
#                 ConnectionType: 'AzureRM'
#                 azureSubscription: 'Azure_DevOps_Service_Connection'
#                 appType: 'webApp'
#                 WebAppName: 'webapp-apiuat-cc-fusionapi-001'
#                 package: '$(Pipeline.Workspace)/drop/'
