trigger:
- main

pool:
  name: Default # Replace with your agent pool name
  demands:
    - agent.os -equals Windows_NT

jobs:
- job: InstallGit
  steps:
    - powershell: |
        $gitInstaller = "https://github.com/git-for-windows/git/releases/download/v2.43.0.windows.1/Git-2.43.0-64-bit.exe"
        $outputPath = "$env:TEMP\GitInstaller.exe"

        Invoke-WebRequest -Uri $gitInstaller -OutFile $outputPath
        Start-Process -FilePath $outputPath -ArgumentList "/VERYSILENT", "/NORESTART" -Wait
        Write-Host "Git installation completed."
      displayName: 'Install Git on Windows Agent'
