trigger:
  branches:
    include:     
      - release

pool:
  name: Default

stages:
- stage: Build
  displayName: 'Deploy from Published Artifact'
  jobs:
  - job: CI
    displayName: 'Continuous Integration'
    steps:
    # Skip NuGet Restore for Leadtools
    - task: NuGetCommand@2
      displayName: Restore NuGet Packages
      inputs:
        command: 'restore'
        restoreSolution: '*/.sln'
        arguments: |
          -Exclude Leadtools.*

    - task: UseDotNet@2
      displayName: 'Install .NET Core SDK'
      inputs:
        packageType: 'sdk'
        version: '8.x'  

    - script: dotnet restore net/DocumentService.csproj
      displayName: 'Restore dependencies .NET'

    - script: dotnet build net/DocumentService.csproj --configuration Release
      displayName: 'Build application'

    - script: dotnet publish net/DocumentService.csproj --configuration Release --output $(Build.ArtifactStagingDirectory)
      displayName: 'Publish Application'

    # # Include the bin folder in the artifact
    # - powershell: |
    #     Copy-Item -Path "$(Build.SourcesDirectory)\bin" -Destination "$(Build.ArtifactStagingDirectory)\bin" -Recurse
    #   displayName: 'Include Bin Folder'

    - task: PublishBuildArtifacts@1
      displayName: 'Publish Build Artifacts'
      inputs:
        pathtoPublish: '$(Build.ArtifactStagingDirectory)'
        ArtifactName: 'drop'
        publishLocation: Container

- stage: DeployQA
  displayName: 'Deploy to QA'
  dependsOn: Build
  jobs:
  - job: CDQA
    displayName: 'Continuous Deployment to QA'
    steps:
    - download: current
      artifact: drop
      displayName: 'Download Build Artifacts'

    - task: UseDotNet@2
      displayName: 'Install .NET Core SDK'
      inputs:
        packageType: 'sdk'
        version: '8.x'  

    # - task: AzureRmWebAppDeployment@4
    #   displayName: 'Azure Web App Deploy to QA'
    #   inputs:
    #     ConnectionType: AzureRM 
    #     azureSubscription: 'Microservices_Connection'
    #     appType: 'webApp'
    #     #WebAppName: 'docviewer.azurewebsites.net' 
    #     WebAppName: 'webapp-msqa-cc-documentviewer'
    #     package: '$(Pipeline.Workspace)/drop'